# Populating rooms
room_types = [
    {name: 'Private room'},
    {name: 'Entire home/apt'},
    {name: 'Shared room'}
]
existing_room_types = RoomType.pluck(:name)
RoomType.create(room_types.select {|r| !r[:name].in?(existing_room_types) })

# Populating Neighbourhood Groups
neighbourhood_groups = [
    {name: 'Brooklyn'},
    {name: 'Manhattan'},
    {name: 'Bronx'},
    {name: 'Queens'},
    {name: 'Staten Island'}
]
existing_neighbourhood_groups = NeighbourhoodGroup.pluck(:name)
NeighbourhoodGroup.create(
    neighbourhood_groups.
        select {|r| !r[:name].in?(existing_neighbourhood_groups) }
)

# Populating Neighbourhoods
neighbourhoods = [
    {name: 'City Island'},
    {name: 'Allerton'},
    {name: 'Ditmars Steinway'},
    {name: 'Astoria'},
    {name: 'Bushwick'},
    {name: 'Gerritsen Beach'},
    {name: 'Soundview'},
    {name: 'Ozone Park'},
    {name: 'Fordham'},
    {name: 'Bay Ridge'},
    {name: 'Whitestone'},
    {name: 'Arrochar'},
    {name: 'Bedford-Stuyvesant'},
    {name: 'Arverne'},
    {name: 'Chelsea'},
    {name: 'Boerum Hill'},
    {name: 'East Village'},
    {name: 'Battery Park City'},
    {name: 'Bayside'},
    {name: 'Prospect-Lefferts Gardens'},
    {name: 'Bay Terrace'},
    {name: 'Baychester'},
    {name: 'Mount Eden'},
    {name: 'East Harlem'},
    {name: 'Chinatown'},
    {name: 'Flatbush'},
    {name: 'Canarsie'},
    {name: 'Bellerose'},
    {name: 'Bensonhurst'},
    {name: 'Bergen Beach'},
    {name: 'Borough Park'},
    {name: 'Briarwood'},
    {name: 'Brighton Beach'},
    {name: 'Brooklyn Heights'},
    {name: 'Harlem'},
    {name: 'Mott Haven'},
    {name: 'Bronxdale'},
    {name: 'Brownsville'},
    {name: 'Downtown Brooklyn'},
    {name: 'Financial District'},
    {name: 'Fort Greene'},
    {name: 'Glen Oaks'},
    {name: 'Kensington'},
    {name: 'Cambria Heights'},
    {name: 'Carroll Gardens'},
    {name: 'Greenpoint'},
    {name: 'Civic Center'},
    {name: 'Dyker Heights'},
    {name: 'Claremont Village'},
    {name: 'Clason Point'},
    {name: 'Clifton'},
    {name: 'Clinton Hill'},
    {name: 'East Elmhurst'},
    {name: 'Hell\'s Kitchen'},
    {name: 'Cobble Hill'},
    {name: 'College Point'},
    {name: 'Crown Heights'},
    {name: 'Gowanus'},
    {name: 'Gramercy'},
    {name: 'Edenwald'},
    {name: 'Concourse'},
    {name: 'Columbia St'},
    {name: 'Concord'},
    {name: 'Concourse Village'},
    {name: 'Coney Island'},
    {name: 'Corona'},
    {name: 'Country Club'},
    {name: 'Mount Hope'},
    {name: 'Cypress Hills'},
    {name: 'DUMBO'},
    {name: 'Dongan Hills'},
    {name: 'Greenwich Village'},
    {name: 'East Flatbush'},
    {name: 'Flushing'},
    {name: 'Forest Hills'},
    {name: 'East New York'},
    {name: 'East Morrisania'},
    {name: 'Elmhurst'},
    {name: 'Emerson Hill'},
    {name: 'Fieldston'},
    {name: 'Eastchester'},
    {name: 'Edgemere'},
    {name: 'Far Rockaway'},
    {name: 'Jamaica Estates'},
    {name: 'Gravesend'},
    {name: 'Flatiron District'},
    {name: 'Flatlands'},
    {name: 'Laurelton'},
    {name: 'Fort Hamilton'},
    {name: 'Fresh Meadows'},
    {name: 'Graniteville'},
    {name: 'Glendale'},
    {name: 'Kew Gardens'},
    {name: 'Great Kills'},
    {name: 'Grymes Hill'},
    {name: 'Midtown'},
    {name: 'Kips Bay'},
    {name: 'Inwood'},
    {name: 'Highbridge'},
    {name: 'Midwood'},
    {name: 'Howard Beach'},
    {name: 'Howland Hook'},
    {name: 'Morningside Heights'},
    {name: 'Jackson Heights'},
    {name: 'Jamaica'},
    {name: 'Little Italy'},
    {name: 'Kingsbridge'},
    {name: 'Morris Park'},
    {name: 'Kew Gardens Hills'},
    {name: 'Murray Hill'},
    {name: 'Morrisania'},
    {name: 'Long Island City'},
    {name: 'Lower East Side'},
    {name: 'Prospect Heights'},
    {name: 'Longwood'},
    {name: 'New Brighton'},
    {name: 'Rego Park'},
    {name: 'West Village'},
    {name: 'Roosevelt Island'},
    {name: 'Park Slope'},
    {name: 'Theater District'},
    {name: 'Manhattan Beach'},
    {name: 'Marble Hill'},
    {name: 'Upper East Side'},
    {name: 'Norwood'},
    {name: 'NoHo'},
    {name: 'Oakwood'},
    {name: 'Morris Heights'},
    {name: 'Mariners Harbor'},
    {name: 'Maspeth'},
    {name: 'Middle Village'},
    {name: 'Melrose'},
    {name: 'Mill Basin'},
    {name: 'Upper West Side'},
    {name: 'Navy Yard'},
    {name: 'New Dorp Beach'},
    {name: 'Nolita'},
    {name: 'Windsor Terrace'},
    {name: 'North Riverdale'},
    {name: 'Rockaway Beach'},
    {name: 'South Slope'},
    {name: 'Sheepshead Bay'},
    {name: 'Washington Heights'},
    {name: 'Parkchester'},
    {name: 'Stuyvesant Town'},
    {name: 'Pelham Bay'},
    {name: 'Queens Village'},
    {name: 'Pelham Gardens'},
    {name: 'Port Morris'},
    {name: 'Port Richmond'},
    {name: 'Williamsburg'},
    {name: 'Sunnyside'},
    {name: 'Red Hook'},
    {name: 'Randall Manor'},
    {name: 'Richmond Hill'},
    {name: 'Ridgewood'},
    {name: 'SoHo'},
    {name: 'Sea Gate'},
    {name: 'Riverdale'},
    {name: 'Shore Acres'},
    {name: 'Silver Lake'},
    {name: 'Woodrow'},
    {name: 'Rosedale'},
    {name: 'South Beach'},
    {name: 'South Ozone Park'},
    {name: 'Springfield Gardens'},
    {name: 'Spuyten Duyvil'},
    {name: 'St. Albans'},
    {name: 'Tompkinsville'},
    {name: 'St. George'},
    {name: 'Stapleton'},
    {name: 'Sunset Park'},
    {name: 'Throgs Neck'},
    {name: 'Todt Hill'},
    {name: 'Tremont'},
    {name: 'Tribeca'},
    {name: 'Two Bridges'},
    {name: 'Woodside'},
    {name: 'Vinegar Hill'},
    {name: 'University Heights'},
    {name: 'Wakefield'},
    {name: 'West Brighton'},
    {name: 'West Farms'},
    {name: 'Woodhaven'},
    {name: 'Woodlawn'},
    {name: 'Westerleigh'},
    {name: 'Williamsbridge'},
    {name: 'Arden Heights'},
    {name: 'Bath Beach'},
    {name: 'Bayswater'},
    {name: 'Belle Harbor'},
    {name: 'Belmont'},
    {name: 'Jamaica Hills'},
    {name: 'Castleton Corners'},
    {name: 'Co-op City'},
    {name: 'Eltingville'},
    {name: 'Midland Beach'},
    {name: 'Hollis'},
    {name: 'Hollis Hills'},
    {name: 'Holliswood'},
    {name: 'Hunts Point'},
    {name: 'New Springville'},
    {name: 'Van Nest'},
    {name: 'Tottenville'},
    {name: 'Rosebank'},
    {name: 'Unionport'},
    {name: 'Olinville'},
    {name: 'Lighthouse Hill'},
    {name: 'Little Neck'},
    {name: 'Neponsit'},
    {name: 'Schuylerville'}
]
existing_neighbourhoods = Neighbourhood.pluck(:name)
Neighbourhood.create(
    neighbourhoods.
        select {|r| !r[:name].in?(existing_neighbourhoods) }
)
